---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

# This reusable workflow from insightsengineering/r.pkg.template will run once a PR to main branch is created.
jobs:
  job-setup:
    name: Should we run R CMD check?
    runs-on: ubuntu-latest
    outputs:
      check_out: ${{ steps.check.outputs.run_r_cmd_check }}
    steps:
      # We can have much more advanced logic to decide which jobs we want to run.
      - name: To check or not to check?
        id: check
        run: |
          echo "run_r_cmd_check=true" >> $GITHUB_OUTPUT
      - name: To style or not to style?
        id: style
        run: |
          echo "run_r_cmd_style=true" >> $GITHUB_OUTPUT

  r-cmd:
    needs: job-setup
    name: R CMD Check 🧬
    # Call a workflow from a given GitHub repository, from a given branch (or tag).
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    if: >
      needs.job-setup.outputs.check_out == 'true'

  r-cmd2:
    needs: job-setup
    name: R CMD Style 🧬
    # Call a workflow from a given GitHub repository, from a given branch (or tag).
    uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@main
    if: >
      needs.job-setup.outputs.style_out == 'true'
